### ISSUE TITLE
Publish v0.2.0 to crates.io

### ISSUE THREAD

**Issue by ticky** [bb010g/rust-hsluv#1]
It looks like v0.2.0 didn’t make it to crates.io!

**Comment by joseluis** [comment]
I was going to report some bugs but it turns out they've already been fixed in the unpublished version.

It would be very nice indeed to update the version in crates.io if you can.

**Comment by mazznoer** [comment]
@bb010g

**Comment by bb010g** [comment]
https://crates.io/crates/hsluv/0.3.0
